# Generated by Django 5.0.1 on 2024-01-16 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_relations', '0002_alter_productorder_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='email',
            field=models.CharField(max_length=201, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='phone_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customer',
            name='phone_number_cc',
            field=models.IntegerField(default=91),
        ),
    ]
