# Generated by Django 5.0.1 on 2024-01-13 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_productattachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='productattachment',
            name='file_name',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
